using Natural Language Understanding
watson-developer-cloud/sentiment-and-emotion pull request #6
Opened 2017-05-21 12:00 UTC by naisofly

Updated the application to use Watson Natural Language Understanding instead of AlchemyLanguage (which is deprecated)

2017-05-23 02:48 UTC, germanattanasio requested changes

2017-05-23 02:48 UTC, germanattanasio commented on README.md
> +[![Deploy to Bluemix](https://bluemix.net/deploy/button.png)](https://bluemix.net/deploy?repository=https://github.com/naisofly/sentiment-and-emotion)
update url

2017-05-23 02:48 UTC, germanattanasio commented on router/index.js
> +      'text' : req.body.text,
keys don't need `'`

2017-05-23 02:48 UTC, germanattanasio commented on views/banner.jade
> +            //- a.resource-item(href='https://github.com/naisofly/sentiment-and-emotion') Fork on Github
url

2017-05-23 02:48 UTC, germanattanasio commented on views/footer.jade
> +		a(href='https://github.com/naisofly/sentiment-and-emotion') Fork on Github
url

2017-05-23 07:16 UTC, naisofly commented
Changes committed

2017-05-23 20:54 UTC, germanattanasio requested changes
2nd round

2017-05-23 20:54 UTC, germanattanasio commented on manifest.yml
> +- name: nai-emotion
use `sentiment-and-emotion`

2017-05-23 20:54 UTC, germanattanasio commented on manifest.yml
> -    SECURE_EXPRESS: 1
Why are you removing the environment variables?

2017-05-23 20:54 UTC, germanattanasio commented on manifest.yml
> +  - nlu-test
This is not the name that you use in the readme

2017-05-23 20:54 UTC, germanattanasio commented on router/index.js
> +    'username': process.env.NATURAL_LANGUAGE_UNDERSTANDING_USERNAME,
Line 21 and 22 can be commented as the SDK will automatically look at those environment variables

2017-05-24 12:29 UTC, naisofly commented
2nd round complete

2017-07-03 11:01 UTC, naisofly commented
@germanattanasio All check have passed, can we merge this pull request? :smile:

2017-07-03 13:15 UTC, germanattanasio approved these changes

2017-07-03 13:16 UTC, merged